- name: Install apt-transport-https required for sury repo
  apt: pkg=apt-transport-https state=present

#- name: Add sury repo
#  copy: src=sury-php.list dest=/etc/apt/sources.list.d/sury-php.list
#  register: dotdeb_repo
#
#- name: Remove old dotdeb repo
#  file: path=/etc/apt/sources.list.d/dotdeb.list state=absent
#
#- name: Install sury gpg key
#  apt_key: url=https://packages.sury.org/php/apt.gpg

- name: Update apt cache
  apt: update_cache=yes

- name: Install ppa:ondrej/php
  apt_repository: repo="ppa:ondrej/php" state=present

- name: Install php7.1 (ubuntu)
  include: php-packages.yml php_package_prefix=php7.1

- name: Set default cli version
  alternatives: name=php path=/usr/bin/php7.1

# Fix https://github.com/oerdnj/deb.sury.org/issues/266
#- name: Disable php*-fpm apache config
#  command: a2disconf {{ item }}
#  with_items:
#    - php5.6-fpm
#    - php7.0-fpm
#  changed_when: False
#  failed_when: False
- name: Enable php*-fpm apache config
  command: a2enconf {{ item }}
  with_items:
    - php7.1-fpm
  changed_when: False
  failed_when: False

- name: Install curl for composer installation
  apt: pkg=curl state=present

- name: Install composer
  shell:
    curl -sS https://getcomposer.org/installer | /usr/bin/php -- --install-dir=/usr/local/bin && /bin/mv -f /usr/local/bin/composer.phar /usr/local/bin/composer
    creates=/usr/local/bin/composer
